-- Step 28: Server-only auto-collection enrollment, device credentials, and batches.
-- Run after step_22_ingest_devices.sql.
--
-- This migration is additive and transaction-wrapped so an error does not leave a
-- partially upgraded schema. CREATE OR REPLACE FUNCTION intentionally replaces
-- the two RPC bodies on rerun while preserving their identities. PostgreSQL also
-- preserves existing function grants on replacement, so the explicit REVOKE and
-- service_role-only GRANT statements below must remain immediately after the RPCs.
-- A future signature or return-type change requires a separately reviewed DROP.
--
-- Hashes and HMACs are generated by the Node API. SQL stores only supplied digest
-- text; enrollment codes and device credentials are never stored in raw form.

begin;

-- The legacy watcher required raw identifiers. New pairing writes only hashes,
-- while existing rows and the legacy unique product_key constraint are preserved.
alter table public.ingest_devices
  alter column product_key drop not null;

alter table public.ingest_devices
  alter column machine_id drop not null;

alter table public.ingest_devices
  add column if not exists machine_id_hash text,
  add column if not exists credential_hash text,
  add column if not exists credential_prefix text,
  add column if not exists status text not null default 'active',
  add column if not exists health_status text not null default 'pending',
  add column if not exists schedule_time time without time zone not null default '16:30:00',
  add column if not exists schedule_timezone text not null default 'America/New_York',
  add column if not exists agent_version text,
  add column if not exists addon_version text,
  add column if not exists ninjatrader_version text,
  add column if not exists last_seen_at timestamptz,
  add column if not exists last_capture_at timestamptz,
  add column if not exists last_success_at timestamptz,
  add column if not exists last_error_code text,
  add column if not exists last_error_at timestamptz,
  add column if not exists revoked_at timestamptz,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

-- ALTER COLUMN is required on rerun because ADD COLUMN IF NOT EXISTS does not
-- correct the default installed by an earlier revision. Existing per-device
-- schedule values are intentionally left untouched.
alter table public.ingest_devices
  alter column schedule_time set default '16:30:00';

do $constraints$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.ingest_devices'::regclass
      and conname = 'ingest_devices_status_check'
  ) then
    alter table public.ingest_devices
      add constraint ingest_devices_status_check
      check (status in ('active', 'revoked'));
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.ingest_devices'::regclass
      and conname = 'ingest_devices_health_status_check'
  ) then
    alter table public.ingest_devices
      add constraint ingest_devices_health_status_check
      check (health_status in ('pending', 'online', 'error', 'update_required'));
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.ingest_devices'::regclass
      and conname = 'ingest_devices_schedule_timezone_check'
  ) then
    alter table public.ingest_devices
      add constraint ingest_devices_schedule_timezone_check
      check (schedule_timezone = 'America/New_York');
  end if;
end
$constraints$;

drop index if exists public.idx_ingest_devices_machine_id_hash_unique;
create unique index if not exists idx_ingest_devices_machine_id_hash_unique
  on public.ingest_devices(machine_id_hash)
  where machine_id_hash is not null
    and status = 'active'
    and revoked_at is null;

create unique index if not exists idx_ingest_devices_credential_hash_unique
  on public.ingest_devices(credential_hash)
  where credential_hash is not null;

create table if not exists public.ingest_enrollments (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  code_hash text not null unique check (code_hash <> ''),
  created_by uuid references public.app_users(id) on delete set null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  consumed_by_device_id uuid references public.ingest_devices(id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint ingest_enrollments_expiry_check check (expires_at > created_at)
);

create index if not exists idx_ingest_enrollments_client_created_at
  on public.ingest_enrollments(client_id, created_at desc);

create index if not exists idx_ingest_enrollments_open_expiry
  on public.ingest_enrollments(expires_at)
  where consumed_at is null and revoked_at is null;

-- Converge older deployments before installing the uniqueness backstop. The
-- newest open code wins; superseded codes become unusable without exposing them.
with ranked_open_enrollments as (
  select id,
         row_number() over (partition by client_id order by created_at desc, id desc) as position
  from public.ingest_enrollments
  where consumed_at is null and revoked_at is null
)
update public.ingest_enrollments as enrollment
set revoked_at = clock_timestamp()
from ranked_open_enrollments as ranked
where enrollment.id = ranked.id
  and ranked.position > 1;

create unique index if not exists idx_ingest_enrollments_one_open_per_client
  on public.ingest_enrollments(client_id)
  where consumed_at is null and revoked_at is null;

create table if not exists public.ingest_pair_rate_limits (
  key_hash text primary key check (key_hash <> ''),
  window_started_at timestamptz not null,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_ingest_pair_rate_limits_updated_at
  on public.ingest_pair_rate_limits(updated_at);

-- CHECK constraints cannot contain a subquery. This immutable helper validates
-- every dynamic row-count value while keeping the batch constraint declarative.
create or replace function public.ingest_row_counts_are_nonnegative(p_row_counts jsonb)
returns boolean
language sql
immutable
strict
set search_path = pg_catalog
as $function$
  select
    jsonb_typeof(p_row_counts) = 'object'
    and not exists (
      select 1
      from jsonb_each(p_row_counts) as entry
      where case
        when jsonb_typeof(entry.value) = 'number' then
          (entry.value #>> '{}')::numeric < 0
          or trunc((entry.value #>> '{}')::numeric) <> (entry.value #>> '{}')::numeric
        else true
      end
    );
$function$;

revoke all on function public.ingest_row_counts_are_nonnegative(jsonb)
  from public, anon, authenticated;
grant execute on function public.ingest_row_counts_are_nonnegative(jsonb)
  to service_role;

create table if not exists public.ingest_batches (
  id uuid primary key default gen_random_uuid(),
  capture_id uuid not null,
  device_id uuid not null references public.ingest_devices(id) on delete restrict,
  client_id uuid not null references public.clients(id) on delete restrict,
  trading_date date not null,
  captured_at timestamptz not null,
  received_at timestamptz not null default now(),
  status text not null default 'received',
  schema_version integer not null,
  storage_path text not null unique,
  content_sha256 text not null,
  byte_count bigint not null,
  row_counts jsonb not null default '{}'::jsonb,
  completeness jsonb not null default '{}'::jsonb,
  daily_import_id uuid references public.daily_imports(id) on delete set null,
  replaces_batch_id uuid references public.ingest_batches(id) on delete set null,
  error_code text,
  error_detail text,
  processed_at timestamptz,
  constraint ingest_batches_device_capture_unique unique (device_id, capture_id),
  constraint ingest_batches_status_check
    check (status in ('received', 'processing', 'processed', 'incomplete', 'late_closed_day', 'failed', 'replaced')),
  constraint ingest_batches_schema_version_check check (schema_version > 0),
  constraint ingest_batches_storage_path_check check (storage_path <> ''),
  constraint ingest_batches_content_sha256_check check (content_sha256 <> ''),
  constraint ingest_batches_byte_count_check check (byte_count >= 0),
  constraint ingest_batches_row_counts_check
    check (public.ingest_row_counts_are_nonnegative(row_counts))
);

-- Named CHECK constraints do not converge through CREATE TABLE IF NOT EXISTS.
-- Recreate this additive lifecycle constraint so rerunning the migration also
-- upgrades databases that installed the earlier Task 2 status set.
alter table public.ingest_batches
  drop constraint if exists ingest_batches_status_check;
alter table public.ingest_batches
  add constraint ingest_batches_status_check
  check (status in (
    'received', 'processing', 'processed', 'incomplete',
    'late_closed_day', 'failed', 'replaced'
  ));

alter table public.daily_imports
  add column if not exists source_type text,
  add column if not exists source_batch_id uuid references public.ingest_batches(id) on delete set null;

do $daily_import_source_constraint$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.daily_imports'::regclass
      and conname = 'daily_imports_source_type_check'
  ) then
    alter table public.daily_imports
      add constraint daily_imports_source_type_check
      check (source_type is null or source_type in ('manual', 'automatic'));
  end if;
end
$daily_import_source_constraint$;

alter table public.ingest_batches
  add column if not exists processing_token uuid,
  add column if not exists processing_lease_expires_at timestamptz,
  add column if not exists processing_attempts integer not null default 0;

do $batch_processing_attempts_constraint$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conrelid = 'public.ingest_batches'::regclass
      and conname = 'ingest_batches_processing_attempts_check'
  ) then
    alter table public.ingest_batches
      add constraint ingest_batches_processing_attempts_check
      check (processing_attempts >= 0);
  end if;
end
$batch_processing_attempts_constraint$;

update public.ingest_batches
set status = 'received', processing_token = null, processing_lease_expires_at = null
where status = 'processing'
  and (processing_token is null or processing_lease_expires_at is null);
update public.ingest_batches
set processing_token = null, processing_lease_expires_at = null
where status <> 'processing'
  and (processing_token is not null or processing_lease_expires_at is not null);

alter table public.ingest_batches
  drop constraint if exists ingest_batches_processing_lease_check;
alter table public.ingest_batches
  add constraint ingest_batches_processing_lease_check
  check (
    (status = 'processing'
      and processing_token is not null
      and processing_lease_expires_at is not null)
    or (status <> 'processing'
      and processing_token is null
      and processing_lease_expires_at is null)
  );

create index if not exists idx_ingest_batches_client_trading_date
  on public.ingest_batches(client_id, trading_date desc);

create index if not exists idx_ingest_batches_device_received_at
  on public.ingest_batches(device_id, received_at desc);

create index if not exists idx_ingest_batches_status_received_at
  on public.ingest_batches(status, received_at);

create or replace function public.prevent_ingest_batch_storage_path_change()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
  if new.storage_path is distinct from old.storage_path then
    raise exception 'ingest batch storage_path is immutable'
      using errcode = '22023';
  end if;
  return new;
end;
$function$;

revoke all on function public.prevent_ingest_batch_storage_path_change()
  from public, anon, authenticated;
grant execute on function public.prevent_ingest_batch_storage_path_change()
  to service_role;

do $trigger$
begin
  if not exists (
    select 1
    from pg_catalog.pg_trigger
    where tgrelid = 'public.ingest_batches'::regclass
      and tgname = 'ingest_batches_storage_path_immutable'
      and not tgisinternal
  ) then
    create trigger ingest_batches_storage_path_immutable
      before update of storage_path on public.ingest_batches
      for each row
      execute function public.prevent_ingest_batch_storage_path_change();
  end if;
end
$trigger$;

-- Private raw-object bucket. The restrictive policy below is ANDed with any
-- permissive policy applicable to anon/authenticated, so even a broad existing
-- Storage policy cannot authorize this bucket. It remains true for other buckets
-- and does not apply to service_role, which retains its normal RLS bypass.
insert into storage.buckets (id, name, public)
values ('ninjatrader-imports', 'ninjatrader-imports', false)
on conflict (id) do update
set name = excluded.name,
    public = false;

do $storage_policy$
begin
  if not exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'ninjatrader-imports deny browser direct access'
  ) then
    create policy "ninjatrader-imports deny browser direct access"
      on storage.objects
      as restrictive
      for all
      to anon, authenticated
      using (bucket_id <> 'ninjatrader-imports')
      with check (bucket_id <> 'ninjatrader-imports');
  end if;
end
$storage_policy$;

alter table public.ingest_enrollments enable row level security;
alter table public.ingest_devices enable row level security;
alter table public.ingest_batches enable row level security;
alter table public.ingest_pair_rate_limits enable row level security;

revoke all on table public.ingest_enrollments from public, anon, authenticated;
revoke all on table public.ingest_devices from public, anon, authenticated;
revoke all on table public.ingest_batches from public, anon, authenticated;
revoke all on table public.ingest_pair_rate_limits from public, anon, authenticated;

grant select, insert, update, delete on table public.ingest_enrollments to service_role;
grant select, insert, update, delete on table public.ingest_devices to service_role;
grant select, insert, update, delete on table public.ingest_batches to service_role;
grant select, insert, update, delete on table public.ingest_pair_rate_limits to service_role;

-- Restrictive deny policies make the browser boundary explicit even if table
-- privileges are accidentally granted to anon/authenticated later.
do $policies$
begin
  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_enrollments'
      and policyname = 'ingest_enrollments deny browser direct access'
  ) then
    create policy "ingest_enrollments deny browser direct access"
      on public.ingest_enrollments
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_devices'
      and policyname = 'ingest_devices deny browser direct access'
  ) then
    create policy "ingest_devices deny browser direct access"
      on public.ingest_devices
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_batches'
      and policyname = 'ingest_batches deny browser direct access'
  ) then
    create policy "ingest_batches deny browser direct access"
      on public.ingest_batches
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;

  if not exists (
    select 1 from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'ingest_pair_rate_limits'
      and policyname = 'ingest_pair_rate_limits deny browser direct access'
  ) then
    create policy "ingest_pair_rate_limits deny browser direct access"
      on public.ingest_pair_rate_limits
      as restrictive
      for all
      to anon, authenticated
      using (false)
      with check (false);
  end if;
end
$policies$;

-- Remove the pre-audit overload from deployments that applied an earlier Step
-- 28 revision. The replacement below owns mutation and audit in one transaction.
drop function if exists public.create_ingest_enrollment(uuid, text, uuid, timestamptz, boolean);

-- Create or replace a one-time enrollment while holding the client lock. This
-- makes eligibility, active-device handling, old-code revocation, and insertion
-- one transaction. Product keys are checked only as server-side eligibility and
-- are never returned by this function.
create or replace function public.create_ingest_enrollment(
  p_client_id uuid,
  p_code_hash text,
  p_created_by uuid,
  p_expires_at timestamptz,
  p_rebind boolean,
  p_action_code text,
  p_reason_code text
)
returns table (
  enrollment_id uuid,
  client_id uuid,
  client_name text,
  expires_at timestamptz,
  revoked_device_ids uuid[]
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
#variable_conflict use_column
declare
  v_client public.clients;
  v_enrollment public.ingest_enrollments;
  v_revoked_device_ids uuid[] := array[]::uuid[];
begin
  if p_client_id is null
    or nullif(btrim(p_code_hash), '') is null
    or p_created_by is null
    or p_expires_at is null
    or p_expires_at <= clock_timestamp() then
    raise exception 'INVALID_ENROLLMENT_REQUEST'
      using errcode = '22023';
  end if;

  if (coalesce(p_rebind, false) and (
        p_action_code is distinct from 'rebound'
        or p_reason_code is null
        or p_reason_code not in ('vps_rebuilt', 'device_replaced', 'support_reset')
      ))
    or (not coalesce(p_rebind, false) and (
        p_action_code is distinct from 'generated'
        or p_reason_code is not null
      )) then
    raise exception 'INVALID_ENROLLMENT_AUDIT_CODE'
      using errcode = '22023';
  end if;

  select client.*
  into v_client
  from public.clients as client
  where client.id = p_client_id
  for update;

  if not found
    or v_client.status is distinct from 'Active'
    or v_client.deleted_at is not null
    or nullif(btrim(v_client.name), '') is null
    or nullif(btrim(v_client.product_key), '') is null then
    raise exception 'CLIENT_NOT_ELIGIBLE'
      using errcode = 'P0001';
  end if;

  -- Every ingest transaction uses client -> enrollment IDs -> device IDs.
  perform 1
  from public.ingest_enrollments as enrollment
  where enrollment.client_id = p_client_id
    and enrollment.consumed_at is null
    and enrollment.revoked_at is null
  order by enrollment.id
  for update;

  perform 1
  from public.ingest_devices as device
  where device.client_id = p_client_id
    and device.status = 'active'
    and device.revoked_at is null
  order by device.id
  for update;

  select coalesce(array_agg(device.id order by device.id), array[]::uuid[])
  into v_revoked_device_ids
  from public.ingest_devices as device
  where device.client_id = p_client_id
    and device.status = 'active'
    and device.revoked_at is null;

  if cardinality(v_revoked_device_ids) > 0 and not coalesce(p_rebind, false) then
    raise exception 'ACTIVE_DEVICE_EXISTS'
      using errcode = 'P0001';
  end if;

  if coalesce(p_rebind, false) then
    update public.ingest_devices
    set status = 'revoked',
        revoked_at = clock_timestamp(),
        credential_hash = null,
        credential_prefix = null
    where client_id = p_client_id
      and status = 'active'
      and revoked_at is null;
  end if;

  update public.ingest_enrollments
  set revoked_at = clock_timestamp()
  where client_id = p_client_id
    and consumed_at is null
    and revoked_at is null;

  insert into public.ingest_enrollments (
    client_id,
    code_hash,
    created_by,
    expires_at
  )
  values (
    p_client_id,
    p_code_hash,
    p_created_by,
    p_expires_at
  )
  returning * into v_enrollment;

  insert into public.audit_logs (
    user_id,
    entity_type,
    entity_id,
    action,
    after_data
  )
  values (
    p_created_by,
    'ingest_enrollment',
    v_enrollment.id,
    case when p_rebind then 'ingest_enrollment.rebound' else 'ingest_enrollment.generated' end,
    jsonb_build_object(
      'clientId', p_client_id,
      'enrollmentId', v_enrollment.id,
      'actionCode', p_action_code,
      'reasonCode', p_reason_code,
      'revokedDeviceIds', v_revoked_device_ids
    )
  );

  return query
  select v_enrollment.id,
         v_enrollment.client_id,
         v_client.name,
         v_enrollment.expires_at,
         v_revoked_device_ids;
end;
$function$;

revoke all on function public.create_ingest_enrollment(uuid, text, uuid, timestamptz, boolean, text, text)
  from public, anon, authenticated;
grant execute on function public.create_ingest_enrollment(uuid, text, uuid, timestamptz, boolean, text, text)
  to service_role;

-- Revoke exactly one enrollment or device after locking both the client and the
-- scoped target. Device credential digests are erased as part of revocation.
drop function if exists public.revoke_ingest_access(uuid, uuid, uuid, text);

create or replace function public.revoke_ingest_access(
  p_client_id uuid,
  p_enrollment_id uuid,
  p_device_id uuid,
  p_reason_code text,
  p_actor_id uuid
)
returns table (
  client_id uuid,
  revoked_kind text,
  revoked_id uuid
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
#variable_conflict use_column
begin
  if p_client_id is null
    or ((p_enrollment_id is null) = (p_device_id is null))
    or p_actor_id is null
    or p_reason_code is null
    or p_reason_code not in ('client_offboarded', 'security_revoke', 'support_reset') then
    raise exception 'INVALID_REVOKE_REQUEST'
      using errcode = '22023';
  end if;

  perform 1
  from public.clients as client
  where client.id = p_client_id
  for update;
  if not found then
    raise exception 'INGEST_ACCESS_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  -- Lock all client enrollments in ID order even for device revocation, keeping
  -- the global client -> enrollment -> device order consistent.
  perform 1
  from public.ingest_enrollments as enrollment
  where enrollment.client_id = p_client_id
  order by enrollment.id
  for update;

  if p_enrollment_id is not null then
    if not exists (
      select 1
      from public.ingest_enrollments as enrollment
      where enrollment.id = p_enrollment_id
        and enrollment.client_id = p_client_id
    ) then
      raise exception 'INGEST_ACCESS_NOT_FOUND'
        using errcode = 'P0002';
    end if;

    update public.ingest_enrollments
    set revoked_at = coalesce(revoked_at, clock_timestamp())
    where id = p_enrollment_id
      and client_id = p_client_id;

    insert into public.audit_logs (user_id, entity_type, entity_id, action, after_data)
    values (
      p_actor_id,
      'ingest_enrollment',
      p_enrollment_id,
      'ingest_enrollment.revoked',
      jsonb_build_object(
        'clientId', p_client_id,
        'id', p_enrollment_id,
        'kind', 'enrollment',
        'reasonCode', p_reason_code
      )
    );

    return query select p_client_id, 'enrollment'::text, p_enrollment_id;
    return;
  end if;

  perform 1
  from public.ingest_devices as device
  where device.id = p_device_id
    and device.client_id = p_client_id
  order by device.id
  for update;
  if not found then
    raise exception 'INGEST_ACCESS_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  update public.ingest_devices
  set status = 'revoked',
      revoked_at = coalesce(revoked_at, clock_timestamp()),
      credential_hash = null,
      credential_prefix = null
  where id = p_device_id
    and client_id = p_client_id;

  insert into public.audit_logs (user_id, entity_type, entity_id, action, after_data)
  values (
    p_actor_id,
    'ingest_device',
    p_device_id,
    'ingest_device.revoked',
    jsonb_build_object(
      'clientId', p_client_id,
      'id', p_device_id,
      'kind', 'device',
      'reasonCode', p_reason_code
    )
  );

  return query select p_client_id, 'device'::text, p_device_id;
end;
$function$;

revoke all on function public.revoke_ingest_access(uuid, uuid, uuid, text, uuid)
  from public, anon, authenticated;
grant execute on function public.revoke_ingest_access(uuid, uuid, uuid, text, uuid)
  to service_role;

-- Durable, serverless-safe limiter. The API supplies only a domain-separated
-- HMAC of the trusted proxy IP, so neither raw IPs nor enrollment codes enter
-- this table. The row lock serializes concurrent attempts for one caller.
create or replace function public.check_ingest_pair_rate_limit(
  p_key_hash text,
  p_now timestamptz,
  p_max_attempts integer,
  p_window_seconds integer,
  p_block_seconds integer
)
returns table (
  allowed boolean,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
#variable_conflict use_column
declare
  v_limit public.ingest_pair_rate_limits;
  v_now timestamptz := coalesce(p_now, clock_timestamp());
  v_next_count integer;
begin
  if nullif(btrim(p_key_hash), '') is null
    or p_max_attempts is null or p_max_attempts <= 0
    or p_window_seconds is null or p_window_seconds <= 0
    or p_block_seconds is null or p_block_seconds <= 0 then
    raise exception 'INVALID_RATE_LIMIT_REQUEST'
      using errcode = '22023';
  end if;

  insert into public.ingest_pair_rate_limits (
    key_hash,
    window_started_at,
    attempt_count,
    updated_at
  )
  values (p_key_hash, v_now, 0, v_now)
  on conflict (key_hash) do nothing;

  select rate_limit.*
  into v_limit
  from public.ingest_pair_rate_limits as rate_limit
  where rate_limit.key_hash = p_key_hash
  for update;

  if v_limit.blocked_until is not null and v_limit.blocked_until > v_now then
    return query
    select false,
           greatest(1, ceil(extract(epoch from (v_limit.blocked_until - v_now)))::integer);
    return;
  end if;

  if v_limit.blocked_until is not null
    or v_now >= v_limit.window_started_at + make_interval(secs => p_window_seconds) then
    update public.ingest_pair_rate_limits
    set window_started_at = v_now,
        attempt_count = 1,
        blocked_until = null,
        updated_at = v_now
    where key_hash = p_key_hash;
    return query select true, 0;
    return;
  end if;

  v_next_count := v_limit.attempt_count + 1;
  if v_next_count > p_max_attempts then
    update public.ingest_pair_rate_limits
    set attempt_count = v_next_count,
        blocked_until = v_now + make_interval(secs => p_block_seconds),
        updated_at = v_now
    where key_hash = p_key_hash;
    return query select false, p_block_seconds;
    return;
  end if;

  update public.ingest_pair_rate_limits
  set attempt_count = v_next_count,
      updated_at = v_now
  where key_hash = p_key_hash;
  return query select true, 0;
end;
$function$;

revoke all on function public.check_ingest_pair_rate_limit(text, timestamptz, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.check_ingest_pair_rate_limit(text, timestamptz, integer, integer, integer)
  to service_role;

-- Atomically consume a one-time enrollment. The enrollment row lock serializes
-- concurrent calls. A retry with the winning machine and credential hashes gets
-- the same device; different hashes cannot reuse the consumed code.
create or replace function public.pair_ingest_device(
  p_code_hash text,
  p_machine_hash text,
  p_credential_hash text,
  p_credential_prefix text,
  p_agent_version text,
  p_addon_version text
)
returns public.ingest_devices
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_enrollment public.ingest_enrollments;
  v_device public.ingest_devices;
begin
  if nullif(btrim(p_code_hash), '') is null
    or nullif(btrim(p_machine_hash), '') is null
    or nullif(btrim(p_credential_hash), '') is null
    or nullif(btrim(p_credential_prefix), '') is null then
    raise exception 'pairing digests and credential prefix are required'
      using errcode = '22023';
  end if;

  select enrollment.*
  into v_enrollment
  from public.ingest_enrollments as enrollment
  where enrollment.code_hash = p_code_hash
  for update;

  if not found then
    raise exception 'enrollment code is invalid'
      using errcode = 'P0002';
  end if;

  if v_enrollment.revoked_at is not null then
    raise exception 'enrollment code is revoked'
      using errcode = '22023';
  end if;

  if v_enrollment.consumed_by_device_id is not null then
    select device.*
    into v_device
    from public.ingest_devices as device
    where device.id = v_enrollment.consumed_by_device_id
    for update;

    if not found
      or v_device.machine_id_hash is distinct from p_machine_hash
      or v_device.credential_hash is distinct from p_credential_hash then
      raise exception 'enrollment code was already consumed'
        using errcode = '22023';
    end if;

    if v_device.status <> 'active' or v_device.revoked_at is not null then
      raise exception 'paired device is revoked'
        using errcode = '22023';
    end if;

    return v_device;
  end if;

  if v_enrollment.consumed_at is not null then
    raise exception 'enrollment code has an invalid consumed state'
      using errcode = '22023';
  end if;

  if v_enrollment.expires_at <= clock_timestamp() then
    raise exception 'enrollment code is expired'
      using errcode = '22023';
  end if;

  insert into public.ingest_devices (
    client_id,
    machine_id_hash,
    credential_hash,
    credential_prefix,
    status,
    agent_version,
    addon_version,
    last_seen_at
  )
  values (
    v_enrollment.client_id,
    p_machine_hash,
    p_credential_hash,
    p_credential_prefix,
    'active',
    p_agent_version,
    p_addon_version,
    clock_timestamp()
  )
  returning * into v_device;

  update public.ingest_enrollments
  set consumed_at = clock_timestamp(),
      consumed_by_device_id = v_device.id
  where id = v_enrollment.id;

  return v_device;
end;
$function$;

revoke all on function public.pair_ingest_device(text, text, text, text, text, text)
  from public, anon, authenticated, service_role;

-- Pairing v2 follows the same client -> enrollment -> device lock order as
-- administration, returns the client display name from the transaction, and
-- commits the success audit with the device mutation. The initial enrollment
-- read is deliberately unlocked and used only to discover the client lock key;
-- the enrollment is reselected and fully revalidated after that lock is held.
create or replace function public.pair_ingest_device_v2(
  p_code_hash text,
  p_machine_hash text,
  p_credential_hash text,
  p_credential_prefix text,
  p_agent_version text,
  p_addon_version text
)
returns table (
  device_id uuid,
  client_id uuid,
  client_name text,
  schedule_time time without time zone,
  schedule_timezone text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
#variable_conflict use_column
declare
  v_client_id uuid;
  v_client public.clients;
  v_enrollment public.ingest_enrollments;
  v_device public.ingest_devices;
  v_constraint_name text;
  v_device_created boolean := false;
begin
  if nullif(btrim(p_code_hash), '') is null
    or nullif(btrim(p_machine_hash), '') is null
    or nullif(btrim(p_credential_hash), '') is null
    or nullif(btrim(p_credential_prefix), '') is null
    or p_agent_version is null
    or p_addon_version is null
    or p_agent_version !~ '^[0-9]{1,5}(\.[0-9]{1,5}){1,3}$'
    or p_addon_version !~ '^[0-9]{1,5}(\.[0-9]{1,5}){1,3}$' then
    raise exception 'INVALID_PAIR_REQUEST'
      using errcode = '22023';
  end if;

  select enrollment.client_id
  into v_client_id
  from public.ingest_enrollments as enrollment
  where enrollment.code_hash = p_code_hash;
  if not found then
    raise exception 'CODE_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  select client.*
  into v_client
  from public.clients as client
  where client.id = v_client_id
  for update;
  if not found
    or v_client.status is distinct from 'Active'
    or v_client.deleted_at is not null
    or nullif(btrim(v_client.name), '') is null then
    raise exception 'CLIENT_INELIGIBLE'
      using errcode = 'P0001';
  end if;

  select enrollment.*
  into v_enrollment
  from public.ingest_enrollments as enrollment
  where enrollment.code_hash = p_code_hash
    and enrollment.client_id = v_client_id
  for update;
  if not found then
    raise exception 'CODE_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  -- Lock every active device deterministically before selecting a consumed
  -- target. The client lock prevents a concurrent admin flow from changing the
  -- set between these steps.
  perform 1
  from public.ingest_devices as device
  where device.status = 'active'
    and device.revoked_at is null
    and (
      device.client_id = v_client_id
      or device.machine_id_hash = p_machine_hash
    )
  order by device.id
  for update;

  if v_enrollment.revoked_at is not null then
    raise exception 'CODE_REVOKED'
      using errcode = 'P0001';
  end if;

  if v_enrollment.consumed_by_device_id is not null then
    select device.*
    into v_device
    from public.ingest_devices as device
    where device.id = v_enrollment.consumed_by_device_id
      and device.client_id = v_client_id
    for update;

    if not found then
      raise exception 'CODE_CONSUMED'
        using errcode = 'P0001';
    end if;
    if v_device.machine_id_hash is distinct from p_machine_hash then
      raise exception 'MACHINE_CONFLICT'
        using errcode = 'P0001';
    end if;
    if v_device.credential_hash is distinct from p_credential_hash then
      raise exception 'NONCE_OR_CREDENTIAL_CONFLICT'
        using errcode = 'P0001';
    end if;
    if v_device.status <> 'active' or v_device.revoked_at is not null then
      raise exception 'DEVICE_REVOKED'
        using errcode = 'P0001';
    end if;

    return query
    select v_device.id, v_client_id, v_client.name,
           v_device.schedule_time, v_device.schedule_timezone;
    return;
  end if;

  if v_enrollment.consumed_at is not null then
    raise exception 'CODE_CONSUMED'
      using errcode = 'P0001';
  end if;
  if v_enrollment.expires_at <= clock_timestamp() then
    raise exception 'CODE_EXPIRED'
      using errcode = 'P0001';
  end if;
  if exists (
    select 1
    from public.ingest_devices as device
    where device.machine_id_hash = p_machine_hash
      and device.status = 'active'
      and device.revoked_at is null
  ) then
    raise exception 'MACHINE_CONFLICT'
      using errcode = 'P0001';
  end if;
  if exists (
    select 1
    from public.ingest_devices as device
    where device.client_id = v_client_id
      and device.status = 'active'
      and device.revoked_at is null
  ) then
    raise exception 'CODE_CONSUMED'
      using errcode = 'P0001';
  end if;

  begin
    insert into public.ingest_devices (
      client_id,
      machine_id_hash,
      credential_hash,
      credential_prefix,
      status,
      agent_version,
      addon_version,
      last_seen_at
    )
    values (
      v_client_id,
      p_machine_hash,
      p_credential_hash,
      p_credential_prefix,
      'active',
      p_agent_version,
      p_addon_version,
      clock_timestamp()
    )
    returning * into v_device;
    v_device_created := true;
  exception
    when unique_violation then
      get stacked diagnostics v_constraint_name = constraint_name;
      if v_constraint_name = 'idx_ingest_devices_machine_id_hash_unique' then
        raise exception 'MACHINE_CONFLICT'
          using errcode = 'P0001';
      elsif v_constraint_name = 'idx_ingest_devices_credential_hash_unique' then
        raise exception 'CREDENTIAL_CONFLICT'
          using errcode = 'P0001';
      else
        raise;
      end if;
  end;

  update public.ingest_enrollments
  set consumed_at = clock_timestamp(),
      consumed_by_device_id = v_device.id
  where id = v_enrollment.id;

  if v_device_created then
    insert into public.audit_logs (user_id, entity_type, entity_id, action, after_data)
    values (
      null,
      'ingest_device',
      v_device.id,
      'ingest_pair.succeeded',
      jsonb_build_object(
        'clientId', v_client_id,
        'deviceId', v_device.id,
        'agentVersion', p_agent_version,
        'addonVersion', p_addon_version
      )
    );
  end if;

  return query
  select v_device.id, v_client_id, v_client.name,
         v_device.schedule_time, v_device.schedule_timezone;
end;
$function$;

revoke all on function public.pair_ingest_device_v2(text, text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.pair_ingest_device_v2(text, text, text, text, text, text)
  to service_role;

-- Record health and liveness under the device row lock. Calls inside the
-- configured interval avoid a write only when every supplied heartbeat field is
-- unchanged. First contact, version/error/status changes, and recovery always
-- bypass throttling. Free-form diagnostic text stays in allowlisted metadata
-- and is deliberately excluded from audit payloads and the RPC result.
create or replace function public.record_ingest_heartbeat(
  p_device_id uuid,
  p_agent_version text,
  p_addon_version text,
  p_ninjatrader_version text,
  p_last_capture_at timestamptz,
  p_last_success_at timestamptz,
  p_last_error_code text,
  p_last_error_message text,
  p_queue_depth bigint,
  p_queue_bytes bigint,
  p_addon_available boolean,
  p_health_status text,
  p_min_interval_seconds integer
)
returns table (
  device_id uuid,
  health_status text,
  throttled boolean,
  schedule_time time without time zone,
  schedule_timezone text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
#variable_conflict use_column
declare
  v_device public.ingest_devices;
  v_now timestamptz := clock_timestamp();
  v_effective_capture_at timestamptz;
  v_effective_success_at timestamptz;
  v_unchanged boolean;
  v_first_online boolean;
  v_recovered boolean;
begin
  if p_device_id is null
    or p_agent_version is null
    or p_addon_version is null
    or p_agent_version !~ '^[0-9]{1,5}(\.[0-9]{1,5}){1,3}$'
    or p_addon_version !~ '^[0-9]{1,5}(\.[0-9]{1,5}){1,3}$'
    or p_ninjatrader_version is null
    or p_ninjatrader_version !~ '^[0-9]{1,5}(\.[0-9]{1,5}){1,3}$'
    or (p_last_error_code is not null and p_last_error_code not in (
      'ninjatrader_not_running',
      'addon_unavailable',
      'capture_timeout',
      'capture_failed',
      'contract_mismatch',
      'queue_capacity_warning',
      'upload_failed',
      'configuration_error'
    ))
    or (p_last_error_message is not null and (
      char_length(p_last_error_message) > 256
      or p_last_error_message ~ '[[:cntrl:]]'
    ))
    or p_queue_depth is null or not (p_queue_depth >= 0)
    or p_queue_depth > 9007199254740991
    or p_queue_bytes is null or not (p_queue_bytes >= 0)
    or p_queue_bytes > 9007199254740991
    or (p_last_capture_at is not null
        and p_last_capture_at > v_now + interval '5 minutes')
    or (p_last_success_at is not null
        and p_last_success_at > v_now + interval '5 minutes')
    or (p_last_success_at is not null
        and p_last_capture_at is not null
        and p_last_success_at > p_last_capture_at)
    or p_health_status is null
    or p_health_status not in ('online', 'error', 'update_required')
    or (p_health_status = 'online' and p_last_error_code is not null)
    or (p_health_status = 'error' and p_last_error_code is null)
    or p_min_interval_seconds is null
    or p_min_interval_seconds not between 1 and 3600 then
    raise exception 'INVALID_HEARTBEAT_REQUEST'
      using errcode = '22023';
  end if;

  select device.*
  into v_device
  from public.ingest_devices as device
  where device.id = p_device_id
  for update;

  if not found
    or v_device.status is distinct from 'active'
    or v_device.revoked_at is not null then
    raise exception 'INVALID_INGEST_DEVICE'
      using errcode = 'P0001';
  end if;

  v_effective_capture_at := case
    when v_device.last_capture_at is null then p_last_capture_at
    when p_last_capture_at is null then v_device.last_capture_at
    else greatest(v_device.last_capture_at, p_last_capture_at)
  end;
  v_effective_success_at := case
    when v_device.last_success_at is null then p_last_success_at
    when p_last_success_at is null then v_device.last_success_at
    else greatest(v_device.last_success_at, p_last_success_at)
  end;

  if v_effective_success_at is not null
    and (v_effective_capture_at is null
         or v_effective_success_at > v_effective_capture_at) then
    raise exception 'INVALID_HEARTBEAT_REQUEST'
      using errcode = '22023';
  end if;

  v_unchanged :=
    v_device.agent_version is not distinct from p_agent_version
    and v_device.addon_version is not distinct from p_addon_version
    and v_device.ninjatrader_version is not distinct from p_ninjatrader_version
    and v_device.last_capture_at is not distinct from v_effective_capture_at
    and v_device.last_success_at is not distinct from v_effective_success_at
    and v_device.last_error_code is not distinct from p_last_error_code
    and v_device.health_status is not distinct from p_health_status
    and (v_device.metadata ->> 'lastErrorMessage') is not distinct from p_last_error_message
    and (v_device.metadata -> 'queueDepth') is not distinct from to_jsonb(p_queue_depth)
    and (v_device.metadata -> 'queueBytes') is not distinct from to_jsonb(p_queue_bytes)
    and (v_device.metadata -> 'addonAvailable') is not distinct from to_jsonb(p_addon_available);

  if v_unchanged
    and v_device.last_seen_at is not null
    and v_now < v_device.last_seen_at + make_interval(secs => p_min_interval_seconds) then
    return query
    select v_device.id,
           v_device.health_status,
           true,
           v_device.schedule_time,
           v_device.schedule_timezone;
    return;
  end if;

  v_first_online := v_device.health_status = 'pending';
  v_recovered := v_device.last_error_code is not null and p_last_error_code is null;

  update public.ingest_devices
  set agent_version = p_agent_version,
      addon_version = p_addon_version,
      ninjatrader_version = p_ninjatrader_version,
      last_seen_at = v_now,
      last_capture_at = v_effective_capture_at,
      last_success_at = v_effective_success_at,
      last_error_code = p_last_error_code,
      last_error_at = case
        when p_last_error_code is null then null
        when last_error_code is distinct from p_last_error_code then v_now
        else coalesce(last_error_at, v_now)
      end,
      health_status = p_health_status,
      metadata = (coalesce(metadata, '{}'::jsonb)
                    - 'lastErrorMessage'
                    - 'queueDepth'
                    - 'queueBytes'
                    - 'addonAvailable')
                 || jsonb_strip_nulls(jsonb_build_object(
                      'lastErrorMessage', p_last_error_message,
                      'queueDepth', p_queue_depth,
                      'queueBytes', p_queue_bytes,
                      'addonAvailable', p_addon_available
                    ))
  where id = p_device_id;

  if v_first_online then
    insert into public.audit_logs (user_id, entity_type, entity_id, action, after_data)
    values (
      null,
      'ingest_device',
      p_device_id,
      'ingest_device.first_online',
      jsonb_build_object(
        'clientId', v_device.client_id,
        'deviceId', p_device_id,
        'healthStatus', p_health_status,
        'agentVersion', p_agent_version,
        'addonVersion', p_addon_version,
        'ninjaTraderVersion', p_ninjatrader_version,
        'lastErrorCode', p_last_error_code
      )
    );
  end if;

  if v_recovered then
    insert into public.audit_logs (user_id, entity_type, entity_id, action, after_data)
    values (
      null,
      'ingest_device',
      p_device_id,
      'ingest_device.recovered',
      jsonb_build_object(
        'clientId', v_device.client_id,
        'deviceId', p_device_id,
        'healthStatus', p_health_status,
        'agentVersion', p_agent_version,
        'addonVersion', p_addon_version,
        'ninjaTraderVersion', p_ninjatrader_version,
        'lastErrorCode', p_last_error_code
      )
    );
  end if;

  return query
  select p_device_id,
         p_health_status,
         false,
         v_device.schedule_time,
         v_device.schedule_timezone;
end;
$function$;

revoke all on function public.record_ingest_heartbeat(
  uuid, text, text, text, timestamptz, timestamptz, text, text,
  bigint, bigint, boolean, text, integer
) from public, anon, authenticated;
grant execute on function public.record_ingest_heartbeat(
  uuid, text, text, text, timestamptz, timestamptz, text, text,
  bigint, bigint, boolean, text, integer
) to service_role;

-- Serializing on the device closes the "no row exists yet" race. Once a claim
-- wins, same-payload retries return that row; a reused capture ID or storage path
-- with different immutable payload metadata is rejected.
create or replace function public.claim_ingest_batch(
  p_device_id uuid,
  p_capture_id uuid,
  p_trading_date date,
  p_captured_at timestamptz,
  p_schema_version integer,
  p_storage_path text,
  p_content_sha256 text,
  p_byte_count bigint,
  p_row_counts jsonb
)
returns public.ingest_batches
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_device public.ingest_devices;
  v_batch public.ingest_batches;
begin
  if p_device_id is null
    or p_capture_id is null
    or p_trading_date is null
    or p_captured_at is null
    or p_schema_version is null
    or p_schema_version <= 0
    or nullif(btrim(p_storage_path), '') is null
    or nullif(btrim(p_content_sha256), '') is null
    or p_byte_count is null
    or p_byte_count < 0
    or p_row_counts is null
    or not public.ingest_row_counts_are_nonnegative(p_row_counts) then
    raise exception 'batch claim metadata is invalid'
      using errcode = '22023';
  end if;

  select device.*
  into v_device
  from public.ingest_devices as device
  where device.id = p_device_id
  for update;

  if not found then
    raise exception 'ingest device is invalid'
      using errcode = 'P0002';
  end if;

  if v_device.status <> 'active' or v_device.revoked_at is not null then
    raise exception 'ingest device is revoked'
      using errcode = '22023';
  end if;

  select batch.*
  into v_batch
  from public.ingest_batches as batch
  where device_id = p_device_id
    and capture_id = p_capture_id
  for update;

  if found then
    if v_batch.trading_date is distinct from p_trading_date
      or v_batch.captured_at is distinct from p_captured_at
      or v_batch.schema_version is distinct from p_schema_version
      or v_batch.storage_path is distinct from p_storage_path
      or v_batch.content_sha256 is distinct from p_content_sha256
      or v_batch.byte_count is distinct from p_byte_count
      or v_batch.row_counts is distinct from p_row_counts then
      raise exception 'capture ID was already claimed with different metadata'
        using errcode = '22023';
    end if;

    return v_batch;
  end if;

  insert into public.ingest_batches (
    capture_id,
    device_id,
    client_id,
    trading_date,
    captured_at,
    status,
    schema_version,
    storage_path,
    content_sha256,
    byte_count,
    row_counts
  )
  values (
    p_capture_id,
    p_device_id,
    v_device.client_id,
    p_trading_date,
    p_captured_at,
    'received',
    p_schema_version,
    p_storage_path,
    p_content_sha256,
    p_byte_count,
    p_row_counts
  )
  returning * into v_batch;

  return v_batch;
end;
$function$;

revoke all on function public.claim_ingest_batch(uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.claim_ingest_batch(uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb)
  to service_role;

-- V2 returns the ownership decision as data. The advisory key serializes the
-- exact device/capture tuple even before a row exists, while the device lock
-- preserves the credential lifecycle ordering used by the other ingest RPCs.
create or replace function public.claim_ingest_batch_v2(
  p_device_id uuid,
  p_capture_id uuid,
  p_trading_date date,
  p_captured_at timestamptz,
  p_schema_version integer,
  p_storage_path text,
  p_content_sha256 text,
  p_byte_count bigint,
  p_row_counts jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_device public.ingest_devices;
  v_batch public.ingest_batches;
begin
  if p_device_id is null
    or p_capture_id is null
    or p_trading_date is null
    or p_captured_at is null
    or p_schema_version is null
    or p_schema_version <= 0
    or nullif(btrim(p_storage_path), '') is null
    or p_storage_path !~ '^[0-9a-f-]+/[0-9]{4}-[0-9]{2}-[0-9]{2}/[0-9a-f-]+\.json\.gz$'
    or p_content_sha256 !~ '^[0-9a-f]{64}$'
    or p_byte_count is null
    or p_byte_count < 0
    or p_row_counts is null
    or not public.ingest_row_counts_are_nonnegative(p_row_counts) then
    raise exception 'batch claim metadata is invalid'
      using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_device_id::text || ':' || p_capture_id::text, 0)
  );

  select device.*
  into v_device
  from public.ingest_devices as device
  where device.id = p_device_id
  for update;

  if not found or v_device.status <> 'active' or v_device.revoked_at is not null then
    raise exception 'ingest device is invalid'
      using errcode = 'P0001';
  end if;

  if p_storage_path is distinct from
    (v_device.client_id::text || '/' || p_trading_date::text || '/' || p_capture_id::text || '.json.gz') then
    raise exception 'batch storage path is invalid'
      using errcode = '22023';
  end if;

  select batch.*
  into v_batch
  from public.ingest_batches as batch
  where device_id = p_device_id
    and capture_id = p_capture_id
  for update;

  if found then
    if v_batch.trading_date is distinct from p_trading_date
      or v_batch.captured_at is distinct from p_captured_at
      or v_batch.schema_version is distinct from p_schema_version
      or v_batch.storage_path is distinct from p_storage_path
      or v_batch.content_sha256 is distinct from p_content_sha256
      or v_batch.byte_count is distinct from p_byte_count
      or v_batch.row_counts is distinct from p_row_counts then
      raise exception 'capture ID was already claimed with different metadata'
        using errcode = '22023';
    end if;
    return jsonb_build_object('claimed', false, 'batch', to_jsonb(v_batch));
  end if;

  insert into public.ingest_batches (
    capture_id, device_id, client_id, trading_date, captured_at, status,
    schema_version, storage_path, content_sha256, byte_count, row_counts
  ) values (
    p_capture_id, p_device_id, v_device.client_id, p_trading_date, p_captured_at,
    'received', p_schema_version, p_storage_path, p_content_sha256,
    p_byte_count, p_row_counts
  )
  returning * into v_batch;

  return jsonb_build_object('claimed', true, 'batch', to_jsonb(v_batch));
end;
$function$;

revoke all on function public.claim_ingest_batch_v2(uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.claim_ingest_batch_v2(uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb)
  to service_role;

-- Persist the same reconciled object consumed by the browser adapter, but in a
-- single server transaction. Empty detail sections intentionally preserve the
-- prior rows, matching the manual replacement safeguard.
create or replace function public.persist_auto_daily_import(
  p_client_id uuid,
  p_source_batch_id uuid,
  p_import_result jsonb
)
returns public.daily_imports
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
#variable_conflict use_column
declare
  v_client public.clients;
  v_batch public.ingest_batches;
  v_daily public.daily_imports;
  v_prior_batch public.ingest_batches;
  v_date date;
  v_item jsonb;
  v_account_name text;
  v_account_id uuid;
  v_snapshot_id uuid;
begin
  if p_client_id is null
    or p_source_batch_id is null
    or jsonb_typeof(p_import_result) <> 'object'
    or nullif(p_import_result ->> 'date', '') is null then
    raise exception 'invalid_auto_daily_import'
      using errcode = '22023';
  end if;

  begin
    v_date := (p_import_result ->> 'date')::date;
  exception when others then
    raise exception 'invalid_auto_daily_import'
      using errcode = '22023';
  end;

  select client.* into v_client
  from public.clients as client
  where client.id = p_client_id
  for update;
  if not found then
    raise exception 'invalid_auto_daily_import'
      using errcode = 'P0002';
  end if;

  select batch.* into v_batch
  from public.ingest_batches as batch
  where batch.id = p_source_batch_id
  for update;
  if not found
    or v_batch.client_id is distinct from p_client_id
    or v_batch.trading_date is distinct from v_date
    or v_batch.status not in ('received', 'processing') then
    raise exception 'invalid_auto_daily_import'
      using errcode = '22023';
  end if;

  select daily.* into v_daily
  from public.daily_imports as daily
  where daily.client_id = p_client_id
    and daily.trading_date = v_date
  for update;
  if found and v_daily.status is not distinct from 'Closed' then
    raise exception 'daily_import_closed'
      using errcode = 'P0001', detail = v_daily.id::text;
  end if;

  if found
    and v_daily.source_batch_id is not null
    and v_daily.source_batch_id is distinct from p_source_batch_id then
    select prior.* into v_prior_batch
    from public.ingest_batches as prior
    where prior.id = v_daily.source_batch_id
      and prior.client_id = p_client_id
    for update;
    update public.ingest_batches
    set status = 'replaced',
        daily_import_id = v_daily.id,
        processing_token = null,
        processing_lease_expires_at = null,
        processed_at = coalesce(processed_at, clock_timestamp())
    where id = v_daily.source_batch_id
      and client_id = p_client_id
      and status in ('processed', 'incomplete', 'processing');
    if found and v_prior_batch.status = 'processing' then
      insert into public.audit_logs (
        user_id, entity_type, entity_id, action, after_data
      ) values (
        null,
        'ingest_batch',
        v_prior_batch.id,
        'ingest_batch_superseded',
        jsonb_build_object(
          'clientId', p_client_id,
          'deviceId', v_prior_batch.device_id,
          'batchId', v_prior_batch.id,
          'replacementBatchId', p_source_batch_id,
          'dailyImportId', v_daily.id,
          'status', 'replaced',
          'rowCounts', v_prior_batch.row_counts,
          'errorCode', null
        )
      );
    end if;
    update public.ingest_batches
    set replaces_batch_id = v_daily.source_batch_id
    where id = p_source_batch_id;
  end if;

  for v_account_name, v_item in
    select entry.key, entry.value
    from jsonb_each(coalesce(p_import_result -> 'accounts', '{}'::jsonb)) as entry
  loop
    insert into public.trading_accounts (
      client_id, legacy_key, account_name, alias, connection, account_type,
      status, payout_state, start_balance, target_profit, max_drawdown_limit,
      risk_level, bullet_bot_pass_type, bullet_bot_direction, algo_stack,
      daily_loss_limit, notes, date_added, date_funded, date_failed,
      date_last_payout, payout_count, updated_at
    ) values (
      p_client_id,
      coalesce(nullif(v_item ->> 'accountName', ''), v_account_name),
      coalesce(nullif(v_item ->> 'accountName', ''), v_account_name),
      coalesce(nullif(v_item ->> 'alias', ''), v_account_name),
      coalesce(v_item ->> 'connection', ''),
      coalesce(nullif(v_item ->> 'accountType', ''), 'Unassigned'),
      coalesce(nullif(v_item ->> 'status', ''), 'Active'),
      coalesce(nullif(v_item ->> 'payoutState', ''), 'Not requested'),
      nullif(v_item ->> 'startBalance', '')::numeric,
      nullif(v_item ->> 'targetProfit', '')::numeric,
      nullif(v_item ->> 'maxDrawdownLimit', '')::numeric,
      coalesce(v_item ->> 'riskLevel', ''),
      coalesce(v_item ->> 'bulletBotPassType', ''),
      coalesce(v_item ->> 'bulletBotDirection', ''),
      coalesce(v_item ->> 'algoStack', ''),
      coalesce(v_item ->> 'dailyLossLimit', ''),
      coalesce(v_item ->> 'notes', ''),
      nullif(v_item ->> 'dateAdded', '')::date,
      nullif(v_item ->> 'dateFunded', '')::date,
      nullif(v_item ->> 'dateFailed', '')::date,
      nullif(v_item ->> 'dateLastPayout', '')::date,
      coalesce(nullif(v_item ->> 'payoutCount', '')::integer, 0),
      clock_timestamp()
    )
    on conflict (client_id, account_name) do update set
      alias = excluded.alias,
      connection = excluded.connection,
      account_type = excluded.account_type,
      status = excluded.status,
      payout_state = excluded.payout_state,
      start_balance = excluded.start_balance,
      target_profit = excluded.target_profit,
      max_drawdown_limit = excluded.max_drawdown_limit,
      risk_level = excluded.risk_level,
      bullet_bot_pass_type = excluded.bullet_bot_pass_type,
      bullet_bot_direction = excluded.bullet_bot_direction,
      algo_stack = excluded.algo_stack,
      daily_loss_limit = excluded.daily_loss_limit,
      notes = excluded.notes,
      date_added = excluded.date_added,
      date_funded = excluded.date_funded,
      date_failed = excluded.date_failed,
      date_last_payout = excluded.date_last_payout,
      payout_count = excluded.payout_count,
      updated_at = excluded.updated_at;
  end loop;

  insert into public.daily_imports (
    client_id, legacy_key, trading_date, imported_at, status, source_summary,
    source_type, source_batch_id, updated_at
  ) values (
    p_client_id,
    coalesce(nullif(p_import_result ->> 'id', ''), p_client_id::text || '-' || v_date::text),
    v_date,
    coalesce(nullif(p_import_result ->> 'importedAt', '')::timestamptz, clock_timestamp()),
    coalesce(nullif(p_import_result ->> 'status', ''), 'Needs review'),
    jsonb_build_object(
      'accounts', jsonb_array_length(coalesce(p_import_result -> 'snapshots', '[]'::jsonb)),
      'strategies', jsonb_array_length(coalesce(p_import_result -> 'strategies', '[]'::jsonb)),
      'orders', jsonb_array_length(coalesce(p_import_result -> 'orders', '[]'::jsonb)),
      'executions', jsonb_array_length(coalesce(p_import_result -> 'executions', '[]'::jsonb)),
      'flags', jsonb_array_length(coalesce(p_import_result -> 'flags', '[]'::jsonb)),
      'source_type', 'automatic',
      'source_batch_id', p_source_batch_id
    ),
    'automatic', p_source_batch_id, clock_timestamp()
  )
  on conflict (client_id, trading_date) do update set
    legacy_key = excluded.legacy_key,
    imported_at = excluded.imported_at,
    status = excluded.status,
    source_summary = excluded.source_summary,
    source_type = excluded.source_type,
    source_batch_id = excluded.source_batch_id,
    updated_at = excluded.updated_at
  returning * into v_daily;

  for v_item in select value from jsonb_array_elements(coalesce(p_import_result -> 'snapshots', '[]'::jsonb))
  loop
    v_account_name := coalesce(v_item ->> 'accountName', '');
    select id into v_account_id from public.trading_accounts
      where client_id = p_client_id and lower(account_name) = lower(v_account_name);
    insert into public.account_snapshots (
      daily_import_id, trading_account_id, account_name, connection,
      gross_realized_pnl, trailing_max_drawdown, account_balance, weekly_pnl,
      unrealized_pnl
    ) values (
      v_daily.id, v_account_id, v_account_name, coalesce(v_item ->> 'connection', ''),
      coalesce(nullif(v_item ->> 'grossRealizedPnl', '')::numeric, 0),
      coalesce(nullif(v_item ->> 'trailingMaxDrawdown', '')::numeric, 0),
      coalesce(nullif(v_item ->> 'accountBalance', '')::numeric, 0),
      coalesce(nullif(v_item ->> 'weeklyPnl', '')::numeric, 0),
      coalesce(nullif(v_item ->> 'unrealizedPnl', '')::numeric, 0)
    ) on conflict (daily_import_id, account_name) do update set
      trading_account_id = excluded.trading_account_id,
      connection = excluded.connection,
      gross_realized_pnl = excluded.gross_realized_pnl,
      trailing_max_drawdown = excluded.trailing_max_drawdown,
      account_balance = excluded.account_balance,
      weekly_pnl = excluded.weekly_pnl,
      unrealized_pnl = excluded.unrealized_pnl;
  end loop;

  if jsonb_array_length(coalesce(p_import_result -> 'strategies', '[]'::jsonb)) > 0 then
    delete from public.strategy_snapshots where daily_import_id = v_daily.id;
    for v_item in select value from jsonb_array_elements(p_import_result -> 'strategies')
    loop
      v_account_name := coalesce(v_item ->> 'accountName', '');
      select id into v_account_id from public.trading_accounts
        where client_id = p_client_id and lower(account_name) = lower(v_account_name);
      select id into v_snapshot_id from public.account_snapshots
        where daily_import_id = v_daily.id and lower(account_name) = lower(v_account_name);
      insert into public.strategy_snapshots (
        daily_import_id, trading_account_id, account_snapshot_id, strategy_name,
        strategy_family, strategy_version, instrument, data_series,
        parameters_raw, params_parsed, direction, enabled, realized, unrealized
      ) values (
        v_daily.id, v_account_id, v_snapshot_id, coalesce(v_item ->> 'strategyName', ''),
        coalesce(v_item ->> 'strategyFamily', ''), coalesce(v_item ->> 'strategyVersion', ''),
        coalesce(v_item ->> 'instrument', ''), coalesce(v_item ->> 'dataSeries', ''),
        coalesce(v_item ->> 'parametersRaw', ''), coalesce(v_item -> 'params', '{}'::jsonb),
        coalesce(v_item ->> 'direction', ''), coalesce((v_item ->> 'enabled')::boolean, false),
        coalesce(nullif(v_item ->> 'realized', '')::numeric, 0),
        coalesce(nullif(v_item ->> 'unrealized', '')::numeric, 0)
      );
    end loop;
  end if;

  if jsonb_array_length(coalesce(p_import_result -> 'orders', '[]'::jsonb)) > 0 then
    delete from public.orders where daily_import_id = v_daily.id;
    for v_item in select value from jsonb_array_elements(p_import_result -> 'orders')
    loop
      select id into v_account_id from public.trading_accounts
        where client_id = p_client_id and lower(account_name) = lower(coalesce(v_item ->> 'accountName', ''));
      insert into public.orders (
        daily_import_id, trading_account_id, external_order_id, strategy_name,
        instrument, action, order_type, quantity, limit_price, stop_price,
        state, filled, avg_price, remaining, name, time_text
      ) values (
        v_daily.id, v_account_id, coalesce(v_item ->> 'id', ''), coalesce(v_item ->> 'strategyName', ''),
        coalesce(v_item ->> 'instrument', ''), coalesce(v_item ->> 'action', ''), coalesce(v_item ->> 'orderType', ''),
        nullif(v_item ->> 'quantity', '')::numeric, nullif(v_item ->> 'limit', '')::numeric,
        nullif(v_item ->> 'stop', '')::numeric, coalesce(v_item ->> 'state', ''),
        nullif(v_item ->> 'filled', '')::numeric, nullif(v_item ->> 'avgPrice', '')::numeric,
        nullif(v_item ->> 'remaining', '')::numeric, coalesce(v_item ->> 'name', ''), coalesce(v_item ->> 'time', '')
      );
    end loop;
  end if;

  if jsonb_array_length(coalesce(p_import_result -> 'executions', '[]'::jsonb)) > 0 then
    delete from public.executions where daily_import_id = v_daily.id;
    for v_item in select value from jsonb_array_elements(p_import_result -> 'executions')
    loop
      select id into v_account_id from public.trading_accounts
        where client_id = p_client_id and lower(account_name) = lower(coalesce(v_item ->> 'accountName', ''));
      insert into public.executions (
        daily_import_id, trading_account_id, external_execution_id,
        external_order_id, strategy_name, instrument, action, quantity, price,
        time_text, entry_exit, position, name, commission, rate, connection
      ) values (
        v_daily.id, v_account_id, coalesce(v_item ->> 'id', ''), coalesce(v_item ->> 'orderId', ''),
        coalesce(v_item ->> 'strategyName', ''), coalesce(v_item ->> 'instrument', ''),
        coalesce(v_item ->> 'action', ''), nullif(v_item ->> 'quantity', '')::numeric,
        nullif(v_item ->> 'price', '')::numeric, coalesce(v_item ->> 'time', ''),
        coalesce(v_item ->> 'entryExit', ''), coalesce(v_item ->> 'position', ''),
        coalesce(v_item ->> 'name', ''), nullif(v_item ->> 'commission', '')::numeric,
        nullif(v_item ->> 'rate', '')::numeric, coalesce(v_item ->> 'connection', '')
      );
    end loop;
  end if;

  delete from public.operational_flags where daily_import_id = v_daily.id;
  for v_item in select value from jsonb_array_elements(coalesce(p_import_result -> 'flags', '[]'::jsonb))
  loop
    select id into v_account_id from public.trading_accounts
      where client_id = p_client_id and lower(account_name) = lower(coalesce(v_item ->> 'accountName', ''));
    insert into public.operational_flags (
      daily_import_id, client_id, trading_account_id, type, severity,
      message, status, resolved_at, resolved_by_user_id
    ) values (
      v_daily.id, p_client_id, v_account_id, coalesce(v_item ->> 'type', 'Import review'),
      coalesce(v_item ->> 'severity', 'Warning'), coalesce(v_item ->> 'message', ''),
      coalesce(v_item ->> 'status', 'Open'), nullif(v_item ->> 'resolvedAt', '')::timestamptz,
      nullif(v_item ->> 'resolvedByUserId', '')::uuid
    );
  end loop;

  return v_daily;
end;
$function$;

revoke all on function public.persist_auto_daily_import(uuid, uuid, jsonb)
  from public, anon, authenticated;
grant execute on function public.persist_auto_daily_import(uuid, uuid, jsonb)
  to service_role;

create or replace function public.finalize_ingest_batch(
  p_batch_id uuid,
  p_device_id uuid,
  p_status text,
  p_daily_import_id uuid,
  p_captured_at timestamptz,
  p_success boolean,
  p_error_code text,
  p_completeness jsonb,
  p_row_counts jsonb,
  p_event_type text
)
returns public.ingest_batches
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_batch public.ingest_batches;
  v_device public.ingest_devices;
begin
  if p_batch_id is null or p_device_id is null
    or p_status not in ('processed', 'incomplete', 'late_closed_day', 'replaced', 'failed')
    or p_captured_at is null
    or p_success is null
    or p_completeness is null
    or p_row_counts is null
    or nullif(btrim(p_event_type), '') is null
    or (p_success and p_status = 'failed')
    or (not p_success and p_status <> 'failed')
    or (p_status = 'failed' and nullif(btrim(p_error_code), '') is null)
    or (p_status <> 'failed' and p_error_code is not null) then
    raise exception 'invalid_batch_finalization'
      using errcode = '22023';
  end if;

  select batch.* into v_batch
  from public.ingest_batches as batch
  where batch.id = p_batch_id
  for update;
  if not found or v_batch.device_id is distinct from p_device_id
    or v_batch.status not in ('received', 'processing') then
    raise exception 'invalid_batch_finalization'
      using errcode = 'P0001';
  end if;

  select device.* into v_device
  from public.ingest_devices as device
  where device.id = p_device_id
  for update;
  if not found or v_device.client_id is distinct from v_batch.client_id then
    raise exception 'invalid_batch_finalization'
      using errcode = 'P0001';
  end if;

  update public.ingest_batches
  set status = p_status,
      daily_import_id = p_daily_import_id,
      completeness = p_completeness,
      error_code = p_error_code,
      error_detail = null,
      processing_token = null,
      processing_lease_expires_at = null,
      processed_at = clock_timestamp()
  where id = p_batch_id
  returning * into v_batch;

  update public.ingest_devices
  set last_capture_at = case
        when last_capture_at is null then p_captured_at
        else greatest(last_capture_at, p_captured_at)
      end,
      last_success_at = case
        when not p_success then last_success_at
        when last_success_at is null then p_captured_at
        else greatest(last_success_at, p_captured_at)
      end,
      last_error_code = case when p_success then null else p_error_code end,
      last_error_at = case when p_success then null else clock_timestamp() end
  where id = p_device_id;

  if p_status = 'late_closed_day' then
    if p_daily_import_id is null then
      raise exception 'closed day link is required'
        using errcode = '22023';
    end if;
    insert into public.operational_flags (
      daily_import_id, client_id, type, severity, message, status
    ) values (
      p_daily_import_id,
      v_batch.client_id,
      'Late automatic snapshot',
      'Warning',
      'A later automatic snapshot was retained and requires explicit Manager review.',
      'Open'
    );
  end if;

  insert into public.audit_logs (
    user_id, entity_type, entity_id, action, after_data
  ) values (
    null,
    'ingest_batch',
    p_batch_id,
    p_event_type,
    jsonb_build_object(
      'clientId', v_batch.client_id,
      'deviceId', p_device_id,
      'batchId', p_batch_id,
      'dailyImportId', p_daily_import_id,
      'status', p_status,
      'rowCounts', p_row_counts,
      'errorCode', p_error_code
    )
  );

  return v_batch;
end;
$function$;

revoke all on function public.finalize_ingest_batch(
  uuid, uuid, text, uuid, timestamptz, boolean, text, jsonb, jsonb, text
) from public, anon, authenticated;
grant execute on function public.finalize_ingest_batch(
  uuid, uuid, text, uuid, timestamptz, boolean, text, jsonb, jsonb, text
) to service_role;

create or replace function public.claim_ingest_batch_v3(
  p_device_id uuid,
  p_capture_id uuid,
  p_trading_date date,
  p_captured_at timestamptz,
  p_schema_version integer,
  p_storage_path text,
  p_content_sha256 text,
  p_byte_count bigint,
  p_row_counts jsonb,
  p_processing_token uuid,
  p_lease_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_client_id uuid;
  v_client public.clients;
  v_device public.ingest_devices;
  v_batch public.ingest_batches;
  v_now timestamptz := clock_timestamp();
  v_retry_after integer;
begin
  if p_device_id is null or p_capture_id is null or p_trading_date is null
    or p_captured_at is null or p_schema_version is null or p_schema_version <= 0
    or nullif(btrim(p_storage_path), '') is null
    or p_content_sha256 !~ '^[0-9a-f]{64}$'
    or p_byte_count is null or p_byte_count < 0
    or p_row_counts is null
    or not public.ingest_row_counts_are_nonnegative(p_row_counts)
    or p_processing_token is null
    or p_lease_seconds is null or p_lease_seconds not between 30 and 600 then
    raise exception 'invalid_batch_claim'
      using errcode = '22023';
  end if;

  -- Resolve the parent without a row lock, then use the same client -> device
  -- -> batch order as enrollment/revocation before trusting the relationship.
  select device.client_id into v_client_id
  from public.ingest_devices as device
  where device.id = p_device_id;
  if not found then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  select client.* into v_client
  from public.clients as client
  where client.id = v_client_id
  for update;
  if not found then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  select device.* into v_device
  from public.ingest_devices as device
  where device.id = p_device_id
  for update;
  if not found or v_device.client_id is distinct from v_client_id
    or v_device.status is distinct from 'active' or v_device.revoked_at is not null then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  if p_storage_path is distinct from
    (v_device.client_id::text || '/' || p_trading_date::text || '/' || p_capture_id::text || '.json.gz') then
    raise exception 'invalid_batch_claim' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_device_id::text || ':' || p_capture_id::text, 0));

  select batch.* into v_batch
  from public.ingest_batches as batch
  where batch.device_id = p_device_id and batch.capture_id = p_capture_id
  for update;
  if found then
    if v_batch.trading_date is distinct from p_trading_date
      or v_batch.captured_at is distinct from p_captured_at
      or v_batch.schema_version is distinct from p_schema_version
      or v_batch.storage_path is distinct from p_storage_path
      or v_batch.content_sha256 is distinct from p_content_sha256
      or v_batch.byte_count is distinct from p_byte_count
      or v_batch.row_counts is distinct from p_row_counts then
      raise exception 'capture_metadata_conflict' using errcode = 'P0001';
    end if;

    if v_batch.status in ('processed', 'incomplete', 'late_closed_day', 'replaced') then
      return jsonb_build_object('outcome', 'terminal', 'retry_after_seconds', 0, 'batch', to_jsonb(v_batch));
    end if;
    if v_batch.status = 'failed' then
      return jsonb_build_object('outcome', 'failed', 'retry_after_seconds', 0, 'batch', to_jsonb(v_batch));
    end if;
    if v_batch.status = 'processing'
      and v_batch.processing_lease_expires_at is not null
      and v_batch.processing_lease_expires_at > v_now then
      v_retry_after := greatest(1, ceil(extract(epoch from (v_batch.processing_lease_expires_at - v_now)))::integer);
      return jsonb_build_object('outcome', 'busy', 'retry_after_seconds', v_retry_after, 'batch', to_jsonb(v_batch));
    end if;

    update public.ingest_batches
    set status = 'processing',
        processing_token = p_processing_token,
        processing_lease_expires_at = v_now + make_interval(secs => p_lease_seconds),
        processing_attempts = processing_attempts + 1
    where id = v_batch.id
    returning * into v_batch;
    return jsonb_build_object('outcome', 'owned', 'retry_after_seconds', 0, 'batch', to_jsonb(v_batch));
  end if;

  insert into public.ingest_batches (
    capture_id, device_id, client_id, trading_date, captured_at, status,
    schema_version, storage_path, content_sha256, byte_count, row_counts,
    processing_token, processing_lease_expires_at, processing_attempts
  ) values (
    p_capture_id, p_device_id, v_device.client_id, p_trading_date, p_captured_at,
    'processing', p_schema_version, p_storage_path, p_content_sha256,
    p_byte_count, p_row_counts, p_processing_token,
    v_now + make_interval(secs => p_lease_seconds), 1
  ) returning * into v_batch;
  return jsonb_build_object('outcome', 'owned', 'retry_after_seconds', 0, 'batch', to_jsonb(v_batch));
end;
$function$;

revoke all on function public.claim_ingest_batch_v3(
  uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb, uuid, integer
) from public, anon, authenticated;
grant execute on function public.claim_ingest_batch_v3(
  uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb, uuid, integer
) to service_role;
revoke execute on function public.claim_ingest_batch_v2(
  uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb
) from service_role;
revoke execute on function public.claim_ingest_batch(
  uuid, uuid, date, timestamptz, integer, text, text, bigint, jsonb
) from service_role;

create or replace function public.release_ingest_batch_lease(
  p_batch_id uuid,
  p_device_id uuid,
  p_processing_token uuid
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_client_id uuid;
  v_client public.clients;
  v_device public.ingest_devices;
  v_batch public.ingest_batches;
begin
  select device.client_id into v_client_id from public.ingest_devices as device
  where device.id = p_device_id;
  if not found then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  select client.* into v_client from public.clients as client
  where client.id = v_client_id for update;
  if not found then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  select device.* into v_device from public.ingest_devices as device
  where device.id = p_device_id for update;
  if not found or v_device.client_id is distinct from v_client_id
    or v_device.status is distinct from 'active' or v_device.revoked_at is not null then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  select batch.* into v_batch from public.ingest_batches as batch
  where batch.id = p_batch_id for update;
  if not found or v_batch.device_id is distinct from p_device_id
    or v_batch.status is distinct from 'processing'
    or v_batch.processing_token is distinct from p_processing_token then
    raise exception 'processing_lease_lost' using errcode = 'P0001';
  end if;
  update public.ingest_batches
  set status = 'received', processing_token = null, processing_lease_expires_at = null
  where id = p_batch_id;
end;
$function$;

revoke all on function public.release_ingest_batch_lease(uuid, uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.release_ingest_batch_lease(uuid, uuid, uuid)
  to service_role;

create or replace function public.persist_auto_daily_import_v2(
  p_client_id uuid,
  p_source_batch_id uuid,
  p_processing_token uuid,
  p_import_result jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_client public.clients;
  v_batch public.ingest_batches;
  v_device public.ingest_devices;
  v_daily public.daily_imports;
  v_prior_batch public.ingest_batches;
begin
  select client.* into v_client from public.clients as client
  where client.id = p_client_id for update;
  if not found then raise exception 'invalid_auto_daily_import' using errcode = 'P0002'; end if;

  select batch.* into v_batch from public.ingest_batches as batch
  where batch.id = p_source_batch_id;
  if not found then raise exception 'invalid_auto_daily_import' using errcode = 'P0002'; end if;

  select device.* into v_device from public.ingest_devices as device
  where device.id = v_batch.device_id for update;
  if not found or v_device.status is distinct from 'active' or v_device.revoked_at is not null
    or v_device.client_id is distinct from p_client_id then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;

  select batch.* into v_batch from public.ingest_batches as batch
  where batch.id = p_source_batch_id for update;
  if v_batch.client_id is distinct from p_client_id
    or v_batch.status is distinct from 'processing'
    or v_batch.processing_token is distinct from p_processing_token
    or v_batch.processing_lease_expires_at is null
    or v_batch.processing_lease_expires_at <= clock_timestamp() then
    raise exception 'processing_lease_lost' using errcode = 'P0001';
  end if;

  select daily.* into v_daily from public.daily_imports as daily
  where daily.client_id = p_client_id and daily.trading_date = v_batch.trading_date
  for update;
  if found and v_daily.status is not distinct from 'Closed' then
    raise exception 'daily_import_closed'
      using errcode = 'P0001', detail = v_daily.id::text;
  end if;
  if found and v_daily.source_batch_id is not null
    and v_daily.source_batch_id is distinct from p_source_batch_id then
    select batch.* into v_prior_batch from public.ingest_batches as batch
    where batch.id = v_daily.source_batch_id for update;
    if found and v_batch.captured_at <= v_prior_batch.captured_at then
      return jsonb_build_object('disposition', 'superseded', 'daily_import', to_jsonb(v_daily));
    end if;
  end if;

  v_daily := public.persist_auto_daily_import(p_client_id, p_source_batch_id, p_import_result);
  return jsonb_build_object('disposition', 'persisted', 'daily_import', to_jsonb(v_daily));
end;
$function$;

revoke all on function public.persist_auto_daily_import_v2(uuid, uuid, uuid, jsonb)
  from public, anon, authenticated;
grant execute on function public.persist_auto_daily_import_v2(uuid, uuid, uuid, jsonb)
  to service_role;
revoke execute on function public.persist_auto_daily_import(uuid, uuid, jsonb)
  from service_role;

-- The legacy finalizer is kept as an internal implementation detail. Only this
-- token-checked wrapper remains executable by service_role.
create or replace function public.finalize_ingest_batch_v2(
  p_batch_id uuid,
  p_device_id uuid,
  p_client_id uuid,
  p_processing_token uuid,
  p_status text,
  p_daily_import_id uuid,
  p_captured_at timestamptz,
  p_success boolean,
  p_error_code text,
  p_completeness jsonb,
  p_row_counts jsonb,
  p_event_type text
)
returns public.ingest_batches
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_client public.clients;
  v_device public.ingest_devices;
  v_batch public.ingest_batches;
  v_daily public.daily_imports;
begin
  if not (
    (p_status in ('processed', 'incomplete') and p_event_type = 'ingest_batch_processed' and p_success)
    or (p_status = 'late_closed_day' and p_event_type = 'ingest_batch_late_closed_day' and p_success)
    or (p_status = 'replaced' and p_event_type = 'ingest_batch_superseded' and p_success)
    or (p_status = 'failed' and p_event_type = 'ingest_batch_failed' and not p_success)
  ) then
    raise exception 'invalid_batch_finalization' using errcode = '22023';
  end if;

  select client.* into v_client from public.clients as client
  where client.id = p_client_id for update;
  if not found then raise exception 'invalid_batch_finalization' using errcode = 'P0002'; end if;
  select device.* into v_device from public.ingest_devices as device
  where device.id = p_device_id for update;
  if not found or v_device.status is distinct from 'active' or v_device.revoked_at is not null
    or v_device.client_id is distinct from p_client_id then
    raise exception 'invalid_ingest_device' using errcode = 'P0001';
  end if;
  select batch.* into v_batch from public.ingest_batches as batch
  where batch.id = p_batch_id for update;
  if not found or v_batch.device_id is distinct from p_device_id
    or v_batch.client_id is distinct from p_client_id
    or v_batch.status is distinct from 'processing'
    or v_batch.processing_token is distinct from p_processing_token
    or v_batch.processing_lease_expires_at is null
    or v_batch.processing_lease_expires_at <= clock_timestamp()
    or v_batch.captured_at is distinct from p_captured_at
    or v_batch.row_counts is distinct from p_row_counts then
    raise exception 'processing_lease_lost' using errcode = 'P0001';
  end if;

  if p_status <> 'failed' then
    select daily.* into v_daily from public.daily_imports as daily
    where daily.id = p_daily_import_id for update;
    if not found or v_daily.client_id is distinct from p_client_id
      or v_daily.trading_date is distinct from v_batch.trading_date then
      raise exception 'invalid_batch_finalization' using errcode = '22023';
    end if;
  elsif p_daily_import_id is not null then
    raise exception 'invalid_batch_finalization' using errcode = '22023';
  end if;

  v_batch := public.finalize_ingest_batch(
    p_batch_id, p_device_id, p_status, p_daily_import_id, p_captured_at,
    p_success, p_error_code, p_completeness, p_row_counts, p_event_type
  );
  update public.ingest_batches
  set processing_token = null, processing_lease_expires_at = null
  where id = p_batch_id
  returning * into v_batch;
  return v_batch;
end;
$function$;

revoke all on function public.finalize_ingest_batch_v2(
  uuid, uuid, uuid, uuid, text, uuid, timestamptz, boolean, text, jsonb, jsonb, text
) from public, anon, authenticated;
grant execute on function public.finalize_ingest_batch_v2(
  uuid, uuid, uuid, uuid, text, uuid, timestamptz, boolean, text, jsonb, jsonb, text
) to service_role;
revoke execute on function public.finalize_ingest_batch(
  uuid, uuid, text, uuid, timestamptz, boolean, text, jsonb, jsonb, text
) from service_role;

commit;
